name: "Deploy frontend"

on:
  push:
    branches: [main]
    paths: ["frontend/**", ".github/workflows/frontend.yml"]

# The aws group ensures that only one workflow at a time can modify the AWS
# infrastructure
concurrency: aws-${{ github.ref }}

jobs:
  build:
    name: "Build frontend"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
      deployments: write
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}
          terraform_wrapper: false

      - name: Terraform Output
        id: terraform-output
        run: terraform output -json

      - name: Build React App
        run: |
          npm ci
          npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cars-frontend
          directory: ./frontend/dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
