name: "Run Terraform"

# On PUSH to main:
#   0) Run terraform fmt
#       (ensure conformity to Terraform style guide)
#   1) Compute Terraform variables and set the TF_WORKSPACE environment variable
#       (TF_WORKSPACE is used by Terraform CLI to select the Terraform Cloud
#       workspace to use)
#   2) Create the workspace of the Branch on Terraform Cloud if it not exists
#       (We run this step even if the workspace should already exists, since we
#       may have deleted the workspace manually)
#   3) Run Terraform init
#       (setup the Terraform Cloud backend)
#   4) Run Terraform validate
#       (ensure syntax is correct)
#   5) Run Terraform apply
#       (deploy the infrastructure)
#
# On PULL REQUEST opened (reopened) or updated to main:
#   0) Run terraform fmt
#       (ensure conformity to Terraform style guide)
#   1) Compute Terraform variables and set the TF_WORKSPACE environment variable
#       (TF_WORKSPACE is used by Terraform CLI to select the Terraform Cloud
#       workspace to use)
#   2) Create the workspace of the Branch on Terraform Cloud if it not exists
#       (We run this step even if the workspace should already exists, since we
#       may have deleted the workspace manually)
#   3) Run Terraform init
#       (setup the Terraform Cloud backend)
#   4) Run Terraform validate
#       (ensure syntax is correct)
#   5) Run Terraform plan, continue if plan fails
#       (show what will be deployed)
#   6) Create of update a comment on the PR with the plan
#       (even if plan failed)
#   7) If the plan failed, exit with error
#   8) Run Terraform apply
#       (deploy the infrastructure)
#
# On PULL REQUEST closed to main:
#   1) Compute Terraform variables and set the TF_WORKSPACE environment variable
#       (TF_WORKSPACE is used by Terraform CLI to select the Terraform Cloud
#       workspace to use)
#   3) Run Terraform init
#       (setup the Terraform Cloud backend)
#   4) Run Terraform destroy, then delete the workspace

on:
  push:
    branches: [main] # [main, dev]
    # TODO: Find a way to reference this file without hardcoding the path
    paths: ["terraform/**", "backend/**", ".github/workflows/terraform.yml"]
  pull_request:
    branches: [main] # [main, dev]
    paths: ["terraform/**", "backend/**", ".github/workflows/terraform.yml"]
    # TODO: the "edited" tag will make the workflow trigger when base branch is
    #       changed (which is what we want), but it will also trigger when the
    #       PR is edited (which we don't want). We leave this edge case open for
    #       now to avoid over-complicating this workflow.
    types: [opened, synchronize, reopened, closed]

env:
  # Secrets to be defined in the github repository
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

# The aws group ensures that only one workflow at a time can modify the AWS
# infrastructure (even if Terraform cloud is already handling concurrent jobs).
concurrency: aws-${{ github.ref }}

jobs:
  # The terraform job is responsible for managing the Terraform lifecycle
  terraform:
    name: "Terraform"
    # WE can limit the job to only run on some branches here
    if: startsWith(github.head_ref, '')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      # Allow the workflow to write to the pull request
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Set the ENV variable based on the branch name
      # WORKSPACE="cars-workspace-branch-${{ github.ref == 'refs/heads/main' && 'prod' || dev }}"
      - name: Set environment
        id: set_env
        run: |
          REF="${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}"
          BRANCH=$(basename "$REF")
          MAIN_WORKSPACE="cars-workspace-branch-main"
          WORKSPACE="cars-workspace-branch-$BRANCH"
          [[ "$BRANCH" == "main" ]] && RESOURCES_PREFIX="" || RESOURCES_PREFIX="$BRANCH"
          INPUT="-input=false -var-file='.tfvars' -var='RESOURCES_PREFIX=$RESOURCES_PREFIX'"

          echo "MAIN_WORKSPACE=$MAIN_WORKSPACE" >> "$GITHUB_OUTPUT"
          echo "WORKSPACE=$WORKSPACE" >> "$GITHUB_OUTPUT"
          echo "BRANCH=$BRANCH" >> "$GITHUB_OUTPUT"
          echo "INPUT=$INPUT" >> "$GITHUB_OUTPUT"

          echo 'TF_WORKSPACE='$WORKSPACE >> $GITHUB_ENV

      - name: Check for changes in backend
        id: check_backend_changes
        if: github.event.action != 'closed'
        run: |
          if git diff --quiet HEAD^ HEAD -- backend ; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Cache Build
        id: cache-build
        if: github.event.action != 'closed'
        uses: actions/cache@v3
        with:
          # the docs say that "the default branch cache is available to other branches".
          path: terraform/branch-dependent/dist
          key: build-output-${{ steps.set_env.outputs.BRANCH }}

      - name: Setup java
        if: github.event.action != 'closed' && !(steps.cache-build.outputs.cache-hit == 'true' && steps.check_backend_changes.outputs.changed == 'false')
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup gradle
        if: github.event.action != 'closed' && !(steps.cache-build.outputs.cache-hit == 'true' && steps.check_backend_changes.outputs.changed == 'false')
        uses: gradle/gradle-build-action@v2

      - name: Build backend
        if: github.event.action != 'closed' && !(steps.cache-build.outputs.cache-hit == 'true' && steps.check_backend_changes.outputs.changed == 'false')
        working-directory: backend
        run: ./gradlew build

      # The setup-terraform action is responsible for installing Terraform and
      # configuring the Terraform CLI to use the Terraform Cloud API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      # Run the Terraform fmt command to check the Terraform code for formatting
      - name: Terraform Format
        id: fmt
        if: github.event.action != 'closed'
        working-directory: terraform/branch-dependent
        run: terraform fmt -check

      # Create the workspace if it does not exist
      - name: Create workspace
        if: github.event.action != 'closed'
        run: |
          curl \
            --header "Authorization: Bearer ${{ env.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data '{
              "data": {
                "attributes": {
                  "name": "${{ steps.set_env.outputs.WORKSPACE }}"
                },
                "type": "workspaces"
              }
            }' \
            https://app.terraform.io/api/v2/organizations/cars-organization/workspaces
        continue-on-error: true

      # Run the Terraform init command to initialize the Terraform working directory
      - name: Terraform Init
        id: init
        working-directory: terraform/branch-dependent
        run: terraform init

      # Run the Terraform validate command to validate the Terraform code
      - name: Terraform Validate
        id: validate
        if: github.event.action != 'closed'
        working-directory: terraform/branch-dependent
        run: terraform validate -no-color

      # Run the Terraform plan command to generate a Terraform execution plan
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        working-directory: terraform/branch-dependent
        # The -var-file option is used to pass the Terraform variables file
        # The -var option is used to pass the ENV variable
        run: terraform plan -no-color ${{ steps.set_env.outputs.INPUT }}
        # Continue the workflow even if the Terraform plan command fails, so that
        # the Terraform plan can be viewed in the pull request.
        # The workflow will be killed later
        continue-on-error: true

      # Create a comment on the pull request with the Terraform plan
      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        env:
          PLAN: ${{ steps.plan.outputs.stdout }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Build the Comment body
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`

            </details>800.513.328

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            // Get the list of comments on the pull request
            const commits = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            // Check if the comment already exists
            const comment = commits.data.find(
              (comment) => comment.body.includes('#### Terraform'));

            // Update or create the comment
            if (comment) {
              await github.rest.issues.updateComment({
                comment_id: comment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }

      # Fail the workflow if the Terraform plan step fails, this allows the pull
      # request message to be written before the workflow is killed
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # Run the Terraform apply command to apply the Terraform execution plan
      - name: Terraform Apply
        if: github.event.action != 'closed'
        working-directory: terraform/branch-dependent
        run: terraform apply -auto-approve ${{ steps.set_env.outputs.INPUT }}

      # Run the Terraform destroy command to destroy the Terraform execution plan
      - name: Terraform Destroy
        if: github.event.action == 'closed'
        working-directory: terraform/branch-dependent
        run: |
          terraform destroy -auto-approve ${{ steps.set_env.outputs.INPUT }}
          TF_WORKSPACE=${{ steps.set_env.outputs.MAIN_WORKSPACE }}
          terraform workspace select ${{ steps.set_env.outputs.MAIN_WORKSPACE }}
          terraform workspace delete ${{ steps.set_env.outputs.WORKSPACE }}
